version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passpass
      - MYSQL_DATABASE=khaddemApp
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  spring_app:
    image: ahmedtlich/ahmedtlich-5nids1-g4-kaddem
    restart: on-failure
    container_name: springapp
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION: '{
        "spring.datasource.url" : "jdbc:mysql://localhost:3306/khaddemApp?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  mysql_data: